# 配置文件

system:
  env: 'dev'
  addr: 6001
  db-type: 'mysql'

# zap日志配置
zap:
  level: 'info'
  format: 'console'
  prefix: '[WEB_MONITOR]'
  directory: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# mysql数据库配置
mysql:
  path: "localhost:3306"
  config: "parseTime=true"
  db-name: "web_monitor_test"
  username: "root"
  password: "root"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true
  log-zap: "zap"

# redis配置
redis:
  db: 0
  addr: 'localhost:6379'
  password: ''
  expiration: 60

# 钉钉机器人推送
dingtalk:
  enable: true # 是否开启钉钉推送
  keyword: 监控平台 # 钉钉推送的关键词